version: 2
updates:
- package-ecosystem: docker
  directory: "/utils/packages/envsubt"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: docker
  directory: "/utils/packages/wazuh-manager-agentless"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
