_meta:
  type: "tenants"
  config_version: 2

# Define your tenants here

admin_tenant:
  reserved: false
  description: "Demo tenant for admin user"

security_tenant:
  reserved: false
  description: "Tenant for Security Analysts"

incident_tenant:
  reserved: false
  description: "Tenant for Incident Responders"

compliance_tenant:
  reserved: false
  description: "Tenant for Compliance Officers"

readonly_tenant:
  reserved: false
  description: "Tenant for Read-Only Users"