_meta:
  type: "rolesmapping"
  config_version: 2

# Define your roles mapping here

## Default roles mapping

all_access:
  reserved: true
  hidden: false
  backend_roles:
    - "admin"
    - "wazuh_super_admin"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]
  description: "Maps admin to all_access"

own_index:
  reserved: false
  hidden: false
  backend_roles: [ ]
  hosts: [ ]
  users:
    - "*"
  and_backend_roles: [ ]
  description: "Allow full access to an index named like the username"

logstash:
  reserved: false
  hidden: false
  backend_roles:
    - "logstash"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]

app_admin:
  reserved: true
  hidden: false
  backend_roles:
    - "wazuh_admin"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]

app_security_analyst:
  reserved: true
  hidden: false
  backend_roles:
    - "wazuh_security_analyst"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]

app_incident_responder:
  reserved: true
  hidden: false
  backend_roles:
    - "wazuh_incident_responder"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]

app_compliance_officer:
  reserved: true
  hidden: false
  backend_roles:
    - "wazuh_compliance_officer"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]

app_read_only:
  reserved: true
  hidden: false
  backend_roles:
    - "wazuh_read_only"
  hosts: [ ]
  users: 
    - "wazuh_read_only"
  and_backend_roles: [ ]

manage_snapshots:
  reserved: true
  hidden: false
  backend_roles:
    - "snapshotrestore"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]

kibana_server:
  reserved: true
  hidden: false
  backend_roles: [ ]
  hosts: [ ]
  users:
    - "kibanaserver"
  and_backend_roles: [ ]

kibana_user:
  reserved: false
  hidden: false
  backend_roles:
    - "kibanauser"
  hosts: [ ]
  users: [ ]
  and_backend_roles: [ ]
  description: "Maps kibanauser to kibana_user"

# Wazuh monitoring and statistics index permissions
manage_wazuh_index:
  reserved: true
  hidden: false
  backend_roles: [ ]
  hosts: [ ]
  users:
    - "kibanaserver"
  and_backend_roles: [ ]
  
security_rest_api_full_access:
  reserved: true
  hidden: false
  backend_roles:
    - "wazuh_admin"
  hosts: []
  users: []
  and_backend_roles: []
