master:
  replicaCount: 1
  resources: ~
  auth:
    enrollment:
      method: "password"
      password: "j60B6_e`jmQ_3z!z"
  
worker: 
  replicaCount: 1
  resources: ~

worker_integration: 
  enabled: false
  resources: ~
  
indexer: 
  replicas: 1
  resources: ~
  
oidc: ~
    
cluster:
  rootCaSecretName: "wazuh-root-ca"

integration:
  jira:
    enabled: false