cluster:
  secret:
    enabled: true
  rootCaSecretName: "<example>-manager-secrets"

indexer:
  auth: ~
  authSecret: "<example>-indexer-secrets"
  s3Snapshot:
    credentialsSecret: "<example>-s3-snapshot-credentials"

apiCred:
  auth: ~
  authSecret: "<example>-api-credentials"

dashboard:
  auth: ~
  authSecret: "<example>-dashboard-secrets"

notification:
  slack:
    externalSecret: "<example>-slack-secrets"

secrets: ~