master:
  replicaCount: 1
  resources: ~
  auth:
    enrollment:
      method: "password"
      password: "j60B6_e`jmQ_3z!z"
  
  persistence:
    enabled: true
    size: 5Gi

worker:
  replicaCount: 1
  resources: ~

worker_agentless:
  replicaCount: 1
  resources: ~

indexer:
  replicas: 1
  resources: ~
  keycloak:
    enabled: false

cluster:
  rootCaSecretName: "wazuh-root-ca"

integration:
  jira:
    enabled: false