master: 
  replicaCount: 1
  resources: ~
  
worker: 
  replicaCount: 1
  resources: ~

worker_integrations: 
  enabled: false
  resources: ~
  
indexer: 
  replicas: 1
  resources: ~
  keycloak: 
    enabled: false
    
cluster:
  rootCaSecretName: "wazuh-root-ca"

integration:
  jira:
    enabled: false