indexer:
  initContainers:
    increase-the-vm-max-map-count: null

master:
  securityContext: null

worker:
  securityContext: null

worker_integration:
  securityContext: null

worker_agentless:
  securityContext: null