{{ with .Values.integration.teams -}}
{{- if and .enabled (not .externalSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.integration-teams" $ }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
stringData:
  TEAMS_CONFIG: |
      <integration>
           <name>custom-teams</name>
           <hook_url>{{ include "common.tplvalues.render" (dict "value" .webhookUrl "context" $) }}</hook_url>
           <level>10</level>
           <alert_format>json</alert_format>
      </integration>
{{- end -}}
{{- end }}