{{- if and .Values.notification.email .Values.notification.email.enabled }}
{{- if not .Values.notification.email.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-email-cred
  namespace: {{ include "common.names.namespace" . }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .Values.indexer.additionalAnnotations "context" . ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.indexer.additionalLabels "context" . ) | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.notification.email.username | quote }}
  password: {{ .Values.notification.email.password | quote }}
{{- end }}
{{- end }}
