{{- if and .Values.indexer.multiTenancy .Values.indexer.multiTenancy.enabled }}
{{- $multiTenancy := .Values.indexer.multiTenancy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" $ }}-multitenancy-creds
  namespace: {{ include "common.names.namespace" $ }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
type: Opaque
stringData:
  {{- range $username, $user := $multiTenancy.internalUsers }}
  {{- if $user.enabled }}
  {{ $username | upper }}_PASSWORD: {{ $user.password | quote }}
  {{- end }}
  {{- end }}
{{- end }}
