hosts:
  - api:
      url: https://{{ include "common.names.fullname" $ }}
      port: 55000
      username: {{ .Values.apiCred.auth.username | quote }}
      password: {{ .Values.apiCred.auth.password | quote }}
      run_as: false

{{- with .Values.opensearchDashboards.branding }}
{{- if .enabled }}

# Custom branding
customization.enabled: true
customization.logo.healthcheck: custom/images/customization.logo.healthcheck.png
customization.logo.reports: custom/images/customization.logo.reports.png
customization.reports.footer: {{ .reports.footer | quote }}
customization.reports.header: |-
{{ .reports.header | indent 2 }}
{{- end }}
{{- end }}