name: Build Wazuh Indexer S3 Docker image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
    paths:
      - '.github/workflows/build-wazuh-indexer-s3.yml'
      - 'utils/packages/wazuh-indexer-s3/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: adorsys-gis/wazuh-indexer-s3
  WAZUH_VERSION: "4.14.2"

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # actions/checkout@v6
        with:
          fetch-depth: "0"
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # docker/setup-buildx-action@v3

      - name: Login to the Docker registry
        id: login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: string
        name: Lowercase the name
        uses: AsZc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # AsZc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # docker/metadata-action@v5
        with:
          tags: |
            type=raw,value=${{ env.WAZUH_VERSION }},enable={{is_default_branch}}
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='Europe/Berlin'}}
            type=semver,enable=true,priority=900,prefix=,suffix=,pattern=,value=
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix={{branch}}-
            type=sha,format=long
            type=sha,format=long,prefix={{branch}}
          images: "${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}"

      - name: Cache Docker layers
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # actions/cache@v4
        if: always()
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # docker/build-push-action@v6
        if: github.event_name != 'pull_request'
        with:
          push: "true"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          platforms: linux/amd64
          build-args: |
            WAZUH_VERSION=${{ env.WAZUH_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          context: ./utils/packages/wazuh-indexer-s3
