{{- $gracefulEnabled := .Values.features.gracefulShutdown.enabled }}
{{- range .Values.tekton.pipelines }}
{{- $isGraceful := contains "graceful" (printf "%v" .name) }}
{{- $enabledRaw := default true .enabled }}
{{- $enabled := not (eq (lower (toString $enabledRaw)) "false") }}
{{- if and $enabled (or (and $gracefulEnabled $isGraceful) (and (not $gracefulEnabled) (not $isGraceful))) }}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "common.tplvalues.render" (dict "value" .name "context" $) }}
  namespace: {{ .namespace | default (include "common.names.namespace" $) }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
{{ with .spec -}}
spec: {{ include "common.tplvalues.render" (dict "value" . "context" $) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
