{{- range .Values.secrets }}
{{- if .enabled | default true }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.tplvalues.render" (dict "value" .name "context" $) }}
  namespace: {{ .namespace | default (include "common.names.namespace" $) }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .additionalLabels "context" $ ) | nindent 4 }}
  annotations:
    {{- include "common.annotations.standard" ( dict "customAnnotations" .additionalAnnotations "context" $ ) | nindent 4 }}
type: {{ .type | default "Opaque" }}
{{ with .data }}
data:
{{- range $k, $v := . }}
  {{ $k }}: {{ include "common.tplvalues.render" (dict "value" $v "context" $) }}
{{- end }}
{{- end }}
{{ with .stringData }}
stringData: {{ include "common.tplvalues.render" (dict "value" . "context" $) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
